### ISSUE TITLE
Handling for starting balance as Asset

### ISSUE THREAD

**Issue by aheadzen** [RJPGriffin/google-forms-gekko-plugin#2]
So sheet gave few errors on first cell because it started with "Sell" not "buy".

So if I am trading on BTC-USD with starting balance in BTC not in USD then the first thing gekko does is sell but sheet tries to calculate profit on this sell which is not possible. I think this particular case can be handled when first order is a sell not a buy.

**Comment by RJPGriffin** [comment]
Yeah, it will show an error in that case, just replace it with a 0 and it will work from there on.
