### ISSUE TITLE
Current price for opened positions?

### ISSUE THREAD

**Issue by xFFFFF** [RJPGriffin/google-forms-gekko-plugin#4]
After buy script could check current price. I would not have to use other tools then your sheet if it had these features.

And if it was still showing the moment of purchase and sale on the chart, then it would be a cosmos at all :)

https://jbuty.com/how-to-get-crypto-currencies-rates-and-more-in-google-sheet-1a57e571bc14

**Comment by RJPGriffin** [comment]
Just considering how's best to implement this... The issue I see is that it would need to be periodically updated to be useful. I can either trigger it from google sheet opening, or periodically. If I do it periodically it calls the function every x seconds 24/7 regardless of whether the sheet is open or not and I'll just be spamming the API...
