### ISSUE TITLE
neuralnet_v2

### ISSUE THREAD

**Issue by hoppy1969** [RJPGriffin/google-forms-gekko-plugin#5]
So I downloaded your neuralnet_v2 strategy to my Gekko.  I tried running a backtest but it doesn't run.  I have put the .js file in the strategy folder and the .toml in the config/strategies folder.  I am reading in the .js file that it requires: var convnetjs = require('convnetjs');
var math = require('mathjs');
var log = require('../core/log.js');
Are those file part of the Gekko when I originally download it?  If not, where to I get those files and what subfolders do they need to be put it?  I'm just starting to use the Gekko, and I'm not understanding how to get these other strategies added to it.  Thanks for any help you can lend.

v/r
Hoppy

**Comment by RJPGriffin** [comment]
Hey,

The neuralnet v2 strat isn't mine... I'm not sure why people keep thinking it is! Also, it doesn't have anything to do with this plugin...

To install the extra dependencies you need to use npm. In terminal/cmd go to the gekko install folder and type "npm install covnetjs" and the same for mathjs. 

Log.js you should already have as its past of gekko...

A better place for this sort out question would be the form or the discord group.

Good luck :)
